=== jankotanime/lego.html-pl/sets.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">


	<xs:element name="mostExpensiveSets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="collection" minOccurs="0" maxOccurs="100"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element name ="set" type ="setType" minOccurs="0" maxOccurs="100"></xs:element>
			</xs:sequence>
			<xs:attribute  name="type" id="type" type="longString"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="setType">
		<xs:sequence>
			<xs:element name="name" type="longString"></xs:element>
			<xs:element name="retailPriceInDollar" type="mediumInclusive"></xs:element>
			<xs:element name="actualMinPriceInDollar" type="mediumInclusive"></xs:element>
			<xs:element name="priceGrowth" type="shortString"></xs:element>
			<xs:element name="ageRestrictions" type="age"></xs:element>
			<xs:choice>
				<xs:element name="images" type="imagesType"></xs:element>
				<xs:element name="links" type="linksType"></xs:element>
			</xs:choice>
			<xs:element name="pieces" type ="piecesType"></xs:element>
			<xs:element name="weight" type="mediumString"></xs:element>
		</xs:sequence>
		<xs:attribute  name="top" id="top" type="shortInclusive"></xs:attribute>
		<xs:attribute  name="identify" id="identify" type="longInclusive"></xs:attribute>
		<xs:attribute  name="avaibleInRetail" id="avaibleInRetail" type="shortString"></xs:attribute>
		<xs:attribute  name="isRetired" id="isRetired" type="shortString"></xs:attribute>
		<xs:attribute  name="inStoreFrom" id="inStoreFrom" type="mediumInclusive"></xs:attribute>
		<xs:attribute name="inStoreUntil" id="inStoreUntil" use="optional" type="mediumInclusive"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="shortString" id="shortString">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"></xs:minLength>
			<xs:maxLength value="6"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>
				   

	<xs:simpleType name="longString" id="longString">
		<xs:restriction base="xs:string">
			<xs:minLength value="5"></xs:minLength>
			<xs:maxLength value="40"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="mediumString" id="mediumString">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"></xs:minLength>
			<xs:maxLength value="20"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="shortInclusive" id="shortInclusive">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"></xs:minInclusive>
			<xs:maxInclusive value="18"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="mediumInclusive" id="mediumInclusive">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"></xs:minInclusive>
			<xs:maxInclusive value="3000"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="longInclusive" id="longInclusive">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1000"></xs:minInclusive>
			<xs:maxInclusive value="100000"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="age" id="age">
		<xs:sequence>
			<xs:element name="minAge" type="shortInclusive"></xs:element>
			<xs:element name="maxAge" type="mediumString"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="piecesType" id="piecesType">
		<xs:sequence>
			<xs:element name="piecesAmount" type="longInclusive"></xs:element>
			<xs:element name="minifiguresAmount" type="shortInclusive"></xs:element>
			<xs:element name="minifigures"  minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:sequence>
							<xs:element name="minifigure"  minOccurs="0" maxOccurs="15"></xs:element>
						</xs:sequence>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="minifigure">
		<xs:sequence>
			<xs:element name="minifigure"></xs:element>
		</xs:sequence>
		<xs:attribute ref="n"></xs:attribute>
	</xs:complexType>

	<xs:attribute name="n" id="n" type="xs:short"></xs:attribute>

	<xs:complexType name="linksType">
		<xs:sequence>
			<xs:element name="link"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="imagesType">
		<xs:sequence>
			<xs:element name="image"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	
	
	
</xs:schema>

=== jankotanime/lego.html-pl/sets/sets.xml
<?xml version="1.0" encoding="utf-8"?>
<mostExpensiveSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sets.xsd">
	<collection type="Star Wars">
		<set top="9" identify="10179" avaibleInRetail="No" isRetired="Yes" inStoreFrom="2007" inStoreUntil="2010">
			<name>Ultimate Collector's Millennium Falcon</name>
			<retailPriceInDollar>500</retailPriceInDollar>
			<actualMinPriceInDollar>1899</actualMinPriceInDollar>
			<priceGrowth>380%</priceGrowth>
			<ageRestrictions>
				<minAge>16</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<images>
				<image source="img/lego-10179-1_medium.jpg">Ultimate Collector's Millennium Falcon</image>
			</images>
			<pieces>
				<piecesAmount>5197</piecesAmount>
				<minifiguresAmount>5</minifiguresAmount>
				<minifigures>
					<minifigure n="1">
						Chewbacca
					</minifigure>
					<minifigure n="2">
						Han Solo
					</minifigure>
					<minifigure n="3">
						Luke Skywalker
					</minifigure>
					<minifigure n="4">
						Obi-Wan Kenobi
					</minifigure>
					<minifigure n="5">
						Prinvess Leia
					</minifigure>
				</minifigures>
			</pieces>
			<weight>10,2kg</weight>
		</set>
		<set top="6" identify="75331" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2022">
			<name>The Razor Crest</name>
			<retailPriceInDollar>600</retailPriceInDollar>
			<actualMinPriceInDollar>600</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>18</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<images>
				<image source="img/lego-75331-1_medium.jpg">The Razor Crest</image>
			</images>
			<pieces>
				<piecesAmount>6187</piecesAmount>
				<minifiguresAmount>5</minifiguresAmount>
				<minifigures>
					<minifigure n="1">
						Mandalorian
					</minifigure>
					<minifigure n="2">
						Mythrol
					</minifigure>
					<minifigure n="3">
						Kuiil
					</minifigure>
					<minifigure n="4">
						Grogi
					</minifigure>
					<minifigure n="5">
						Blurrg
					</minifigure>
				</minifigures>
			</pieces>
			<weight>Around 9kg</weight>
		</set>
		<set top="3" identify="75252" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2019">
			<name>Imperial Star Destroyer</name>
			<retailPriceInDollar>700</retailPriceInDollar>
			<actualMinPriceInDollar>700</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>16</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<links>
				<link source="https://www.lego.com/en-us/product/imperial-star-destroyer-75252">Imperial Star Destroyer</link>
			</links>
			<pieces>
				<piecesAmount>4784</piecesAmount>
				<minifiguresAmount>2</minifiguresAmount>
				<minifigures>
					<minifigure n="1">
						Imperial Officer
					</minifigure>
					<minifigure n="2">
						Imperial Officer
					</minifigure>
				</minifigures>
			</pieces>
			<weight>12,5</weight>
		</set>
		<set top="2" identify="75313" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2021">
			<name>AT-AT</name>
			<retailPriceInDollar>850</retailPriceInDollar>
			<actualMinPriceInDollar>850</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>18</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<links>
				<link source="https://www.lego.com/en-us/product/imperial-star-destroyer-75252">AT-AT</link>
			</links>
			<pieces>
				<piecesAmount>6785</piecesAmount>
				<minifiguresAmount>9</minifiguresAmount>
				<minifigures>
					<minifigure n="1">
						AT-AT Driver
					</minifigure>
					<minifigure n="2">
						AT-AT Driver
					</minifigure>
					<minifigure n="3">
						General Maximillian Veers
					</minifigure>
					<minifigure n="4">
						Luke Skywalker
					</minifigure>
					<minifigure n="5">
						Snowtrooper Commander
					</minifigure>
					<minifigure n="6">
						Snowtrooper
					</minifigure>
					<minifigure n="7">
						Snowtrooper
					<minifigure n="8">
						Snowtrooper
					</minifigure>
					<minifigure n="9">
						Snowtrooper
					</minifigure>
					</minifigure>
				</minifigures>
			</pieces>
			<weight>10,7kg</weight>
		</set>
		<set top="1" identify="75192" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2017">
			<name>Millennium Falcon</name>
			<retailPriceInDollar>850</retailPriceInDollar>
			<actualMinPriceInDollar>850</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>16</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<links>
				<link source="https://www.lego.com/en-us/product/imperial-star-destroyer-75252">Millennium Falcon</link>
			</links>
			<pieces>
				<piecesAmount>7541</piecesAmount>
				<minifiguresAmount>8</minifiguresAmount>
				<minifigures>
					<minifigure n="1">
						BB-8
					</minifigure>
					<minifigure n="2">
						C-3PO
					</minifigure>
					<minifigure n="3">
						Chewbacca
					</minifigure>
					<minifigure n="4">
						Finn
					</minifigure>
					<minifigure n="5">
						Han Solo
					</minifigure>
					<minifigure n="6">
						Old Han Solo
					</minifigure>
					<minifigure n="7">
						Princess Leia
					</minifigure>
					<minifigure n="8">
						Rey
					</minifigure>
				</minifigures>
			</pieces>
			<weight>13,2kg</weight>
		</set>
	</collection>
	<collection type="Icons">
		<set top="7" identify="10276" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2022">
			<name>Colosseum</name>
			<retailPriceInDollar>550</retailPriceInDollar>
			<actualMinPriceInDollar>550</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>18</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<images>
				<image source="img/lego-10276-1_medium.jpg">Collosseum</image>
			</images>
			<pieces>
				<piecesAmount>9036</piecesAmount>
				<minifiguresAmount>0</minifiguresAmount>
			</pieces>
			<weight>10,8kg</weight>
		</set>
		<set top="5" identify="10307" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2022">
			<name>Eiffel Tower</name>
			<retailPriceInDollar>630</retailPriceInDollar>
			<actualMinPriceInDollar>630</actualMinPriceInDollar>
			<priceGrowth>0</priceGrowth>
			<ageRestrictions>
				<minAge>18</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<images>
				<image source="img/lego-10307-1_medium.jpg">Eiffel Tower</image>
			</images>
			<pieces>
				<piecesAmount>10001</piecesAmount>
				<minifiguresAmount>0</minifiguresAmount>
			</pieces>
			<weight>8,9kg</weight>
		</set>
		<set top="4" identify="10294" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2021">
			<name>Titanic</name>
			<retailPriceInDollar>680</retailPriceInDollar>
			<actualMinPriceInDollar>680</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>18</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<images>
				<image source="img/lego-10294-1_medium.jpg">Titanic</image>
			</images>
			<pieces>
				<piecesAmount>9090</piecesAmount>
				<minifiguresAmount>0</minifiguresAmount>
			</pieces>
			<weight>14kg</weight>
		</set>
	</collection>
	<collection>
		<set top="10" identify="42131" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2021">
			<name>Cat D11 Bulldozer</name>
			<retailPriceInDollar>500</retailPriceInDollar>
			<actualMinPriceInDollar>500</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>18</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<images>
				<image source="img/lego-42131-1_medium.jpg">Cat D11 Bulldozer</image>
			</images>
			<pieces>
				<piecesAmount>3854</piecesAmount>
				<minifiguresAmount>0</minifiguresAmount>
			</pieces>
			<weight>6,6kg</weight>
		</set>
	</collection>
	<collection>
		<set top="8" identify="76210" avaibleInRetail="Yes" isRetired="No" inStoreFrom="2022">
			<name>Hulkbuster​</name>
			<retailPriceInDollar>550</retailPriceInDollar>
			<actualMinPriceInDollar>550</actualMinPriceInDollar>
			<priceGrowth>none</priceGrowth>
			<ageRestrictions>
				<minAge>18</minAge>
				<maxAge>Unlimited</maxAge>
			</ageRestrictions>
			<images>
				<image source="img/lego-76210-1_medium.jpg">Hulkbuster</image>
			</images>
			<pieces>
				<piecesAmount>4049</piecesAmount>
				<minifiguresAmount>1</minifiguresAmount>
				<minifigures>
					<minifigure n="1">

					</minifigure>
				</minifigures>
			</pieces>
			<weight>10kg</weight>
		</set>
	</collection>
</mostExpensiveSets>
